import type { Draft } from "../../../src/types.ts";

// Kept as literal lines so shell parameter expansions survive TypeScript unchanged.
const RETRY_SCRIPT = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  'export PGHOST="${PGHOST:-/tmp}" PGPORT="${PGPORT:-5440}" PGUSER="${PGUSER:-postgres}" PGDATABASE="${PGDATABASE:-lab}"',
  "retry_dir=$(mktemp -d /tmp/pg-retry-XXXXXX)",
  "retry_schema=retry_$(date +%s)_$$",
  "retry_app=$retry_schema",
  "retry_gate=$$",
  "retry_controller=",
  "retry_attempt_pid=",
  "retry_psql=(psql -X -q -A -t -v ON_ERROR_STOP=1)",
  "cleanup() {",
  "  retry_exit=$?",
  "  trap - EXIT INT TERM",
  "  set +e",
  '  [[ -n "$retry_attempt_pid" ]] && kill "$retry_attempt_pid" 2>/dev/null',
  '  [[ -n "$retry_controller" ]] && kill "$retry_controller" 2>/dev/null',
  "  exec 3>&-",
  '  [[ -n "$retry_attempt_pid" ]] && wait "$retry_attempt_pid" 2>/dev/null',
  '  [[ -n "$retry_controller" ]] && wait "$retry_controller" 2>/dev/null',
  '  "${retry_psql[@]}" -c "drop schema if exists $retry_schema cascade" >"$retry_dir/cleanup.log" 2>&1',
  '  echo "Evidence: $retry_dir"',
  '  exit "$retry_exit"',
  "}",
  "trap cleanup EXIT",
  "trap 'exit 130' INT",
  "trap 'exit 143' TERM",
  "",
  '"${retry_psql[@]}" -v schema="$retry_schema" <<\'SQL\'',
  'create schema :"schema";',
  'set search_path to :"schema";',
  "create table account(id int primary key, balance int not null);",
  "insert into account values (1,100);",
  "create table effect(request_id text primary key, balance_after int not null);",
  "SQL",
  "",
  "# Keep a controller connection alive. Its advisory lock is a lab scheduling gate.",
  'mkfifo "$retry_dir/control.sql"',
  '"${retry_psql[@]}" -v gate="$retry_gate" <"$retry_dir/control.sql" >"$retry_dir/control.log" 2>&1 &',
  "retry_controller=$!",
  'exec 3>"$retry_dir/control.sql"',
  "printf 'select pg_advisory_lock(:gate);\\n\\\\echo gate_ready\\n' >&3",
  "retry_deadline=$((SECONDS+10))",
  "until rg -q '^gate_ready$' \"$retry_dir/control.log\"; do",
  '  if (( SECONDS >= retry_deadline )) || ! kill -0 "$retry_controller" 2>/dev/null; then',
  "    echo 'Controller did not become ready' >&2",
  "    exit 1",
  "  fi",
  "  sleep 0.05",
  "done",
  "",
  "cat >\"$retry_dir/transaction.sql\" <<'SQL'",
  "\\set VERBOSITY sqlstate",
  'set search_path to :"schema";',
  "begin isolation level repeatable read;",
  "select balance from account where id=1 \\gset",
  "\\if :first",
  "select pg_advisory_xact_lock(:gate);",
  "\\endif",
  "update account set balance=:balance-10 where id=1 returning balance;",
  "insert into effect values ('request-42', :balance-10);",
  "commit;",
  "SQL",
  "",
  "retry_succeeded=false",
  "for retry_attempt in 1 2 3; do",
  "  retry_first=false",
  '  [[ "$retry_attempt" == 1 ]] && retry_first=true',
  '  PGAPPNAME="$retry_app" timeout 20s "${retry_psql[@]}" -v schema="$retry_schema" \\',
  '    -v gate="$retry_gate" -v first="$retry_first" -f "$retry_dir/transaction.sql" \\',
  '    >"$retry_dir/attempt-$retry_attempt.log" 2>&1 &',
  "  retry_attempt_pid=$!",
  '  if [[ "$retry_first" == true ]]; then',
  "    # An advisory wait proves the first snapshot exists before the competing commit.",
  "    retry_deadline=$((SECONDS+10))",
  "    while :; do",
  "      retry_waiting=$(\"${retry_psql[@]}\" -c \"select count(*) from pg_stat_activity where application_name='$retry_app' and wait_event_type='Lock' and wait_event='advisory'\")",
  '      [[ "$retry_waiting" == 1 ]] && break',
  '      if (( SECONDS >= retry_deadline )) || ! kill -0 "$retry_attempt_pid" 2>/dev/null; then',
  "        echo 'First attempt never reached its snapshot gate' >&2",
  "        exit 1",
  "      fi",
  "      sleep 0.05",
  "    done",
  '    "${retry_psql[@]}" -c "update $retry_schema.account set balance=balance+5 where id=1"',
  "    printf 'select pg_advisory_unlock(:gate);\\n' >&3",
  "  fi",
  '  if wait "$retry_attempt_pid"; then retry_status=0; else retry_status=$?; fi',
  "  retry_attempt_pid=",
  '  cat "$retry_dir/attempt-$retry_attempt.log"',
  '  echo "attempt=$retry_attempt status=$retry_status" | tee -a "$retry_dir/attempts.log"',
  '  if [[ "$retry_status" == 0 ]]; then',
  "    retry_succeeded=true",
  "    break",
  "  fi",
  '  if [[ "$retry_status" != 3 ]] || ! rg -q \'ERROR: +40001($|[^0-9A-Z])\' "$retry_dir/attempt-$retry_attempt.log"; then',
  "    echo 'Not a classified serialization failure; refusing to retry' >&2",
  "    exit 1",
  "  fi",
  "  # Each iteration creates a new connection and transaction, including the read/decision.",
  "  sleep 0.1",
  "done",
  "[[ \"$retry_succeeded\" == true ]] || { echo 'Retry budget exhausted' >&2; exit 1; }",
  'retry_result=$("${retry_psql[@]}" -c "select balance,(select count(*) from $retry_schema.effect) from $retry_schema.account where id=1")',
  'echo "balance_and_effect_count=$retry_result"',
  "[[ \"$retry_result\" == '95|1' ]] || { echo 'Unexpected final state' >&2; exit 1; }",
  "[[ \"$retry_attempt\" == 2 ]] || { echo 'The controlled conflict was not observed exactly once' >&2; exit 1; }",
  "echo 'Observed one aborted attempt, a fresh successful transaction, and one committed effect.'",
].join("\n");

export const RETRY: Draft = {
  slug: "retry-loop-and-idempotency",
  title: "Retry the complete transaction after a known serialization failure",
  difficulty: "advanced",
  prerequisites: ["serializable-ssi"],
  tags: ["serialization-failure", "retries", "transactions"],
  revision: 4,
  reading: 'PostgreSQL 14 Internals, Chapter 2 "Isolation" (section "Serializable")',
  readingNotes:
    "Chapter 2 explains why a serialization failure can require a new attempt. This lesson adds the client boundary: a complete transaction, including its read and decision, starts again in a fresh connection. The shell scheduling gate and attempt logs are course additions. Read after observing the failure and recovery.",
  overview:
    "A serialization failure tells the client that its transaction did not commit. This experiment deliberately changes a balance after the first attempt takes its snapshot, then runs a bounded client retry loop. You will identify which attempt failed, which state survived, and why the second attempt must repeat the read as well as the write.",
  syntaxBreakdown:
    "### In plain terms\n\nThe shell plays the application. One connection holds a scheduling lock; a first transaction reads a balance and waits at that lock while a competing connection commits a change. The application classifies the resulting database error and starts a fresh transaction. The scheduling lock exists only to make this experiment reproducible; it is not part of the application's retry algorithm.\n\n### What you are learning\n\n- A known serialization failure aborts an attempt. Retrying database-only transactional work is different from retrying after an unknown commit outcome.\n- The retry includes the read, decision and write. Reusing the old balance would repeat the stale decision.\n- Attempt logs live outside the failed transaction. Their evidence survives when its database changes do not.\n- Retry limits and error classification are part of the client contract. Permission errors, SQL bugs and exhausted deadlines are not silently retried here.\n\n### Piece by piece\n\n- **set -euo pipefail**, **export**, and the **retry_psql array** configure the shell and database client. The options stop on unhandled errors, reject unset variables and report failing pipelines. PGHOST/PGPORT/PGUSER/PGDATABASE select your disposable lab; supplied values override the course defaults. The array preserves argument boundaries. psql -X ignores startup customizations, -q suppresses routine chatter, -A/-t print unaligned values without headings, and -v ON_ERROR_STOP=1 makes SQL errors end the client with status 3.\n- **mktemp -d**, **date +%s**, and **$$** give this run its own evidence directory, schema and scheduling identity. The schema name contains generated numeric components, not user SQL. The evidence path is printed at exit; it contains each attempt and cleanup outcome.\n- **trap**, **kill**, **wait**, and **exec 3>&-** clean up owned background clients and the command pipe. EXIT preserves the original result code. INT/TERM become nonzero exits. kill targets only PIDs this script started, wait reaps them, and closing descriptor 3 releases the FIFO writer. DROP SCHEMA CASCADE removes only this run's generated schema; the logs remain.\n- **mkfifo**, **&**, **$!**, and **exec 3>...** connect a persistent psql controller to a named pipe. The shell retains its write end, so later commands reach the same controller session. The controller holds pg_advisory_lock until explicitly told to unlock. This session lock is a deterministic scheduling gate, not a timed lease.\n- **printf**, **pg_advisory_lock**, **\\echo**, and **rg** establish controller readiness. printf writes SQL plus a psql marker into the pipe. rg checks that marker in the controller log. The SECONDS deadline and kill -0 check bound waiting and detect a dead controller; sleep 0.05 limits polling frequency but is not evidence of readiness.\n- **cat with a quoted here-document** writes the transaction script without expanding its psql variables in the shell. SET search_path restricts unqualified names to the generated schema. BEGIN ISOLATION LEVEL REPEATABLE READ pins a snapshot; SELECT balance with \\gset stores the value in a psql variable.\n- **\\if :first** uses a boolean psql argument to gate only the first attempt. pg_advisory_xact_lock waits for the controller's session lock on the same key; its lifetime ends with the attempt's transaction. UPDATE and the effect receipt belong to one commit.\n- **PGAPPNAME** labels the attempt connection. The observer reads pg_stat_activity for that label and Lock/advisory, proving the first read occurred before the competing update. The observer's UPDATE is its own committed transaction. Sending pg_advisory_unlock to the controller releases the first attempt into the conflict.\n- **timeout 20s**, **if wait ...**, and **VERBOSITY sqlstate** preserve the actual attempt outcome. timeout bounds each client process. The if captures failure without set -e exiting before classification. psql prints SQLSTATE 40001 for the controlled failure. Only status 3 together with that SQLSTATE qualifies for retry; a client timeout or a different error stops the experiment.\n- **for retry_attempt in 1 2 3** limits attempts. Each iteration starts a new psql connection and executes the whole transaction file. The short delay limits immediate retries in this demonstration; a production policy should fit the caller's remaining deadline and contention behavior.\n- **tee -a**, **cat**, and the final assertions expose durable evidence. attempts.log records every exit status outside the database. The final query returns balance and receipt count; assertions check both the business state and that exactly one injected conflict happened.\n",
  expectedResult:
    "The first client ends with SQLSTATE 40001 and status 3. Its balance change and receipt do not commit. The competitor has committed +5. Attempt 2 reads 105, subtracts 10 and commits balance 95 with one effect row; its status is 0. The script asserts balance_and_effect_count=95|1 and exactly two attempts. Absolute PIDs, schema names and paths vary. The evidence directory retains both attempt logs. A different SQL error, a missing readiness condition or an exhausted deadline is a failed experiment, not a passing retry.",
  systemsLens:
    "Transaction retry is a client protocol around an atomic storage operation. The database reports the failed attempt, while the client owns the retry budget and repeats the decision on fresh state. The example has only transactional database effects, so the known-aborted attempt has nothing external to deduplicate. A timeout that hides whether COMMIT succeeded requires a stable request identity and result recovery; the unknown-outcome experiment handles that separate case. Safety of committed serializable results does not depend on retrying forever: the application can instead report a failure.",
  challenge:
    "Change the competing increment from 5 to 20 and predict the final balance before rerunning. Update the corresponding final assertion only after writing the prediction. Keep the initial balance, decrement, gate and two-attempt requirement the same; identify which log proves the failed attempt did not subtract ten.",
  caution:
    "Run in a shell connected to the disposable course lab. The script creates and removes a uniquely named scratch schema and starts two owned client processes. It leaves evidence under /tmp/pg-retry-*. It does not retry arbitrary SQL errors or simulate a real network failure. Do not interrupt cleanup by killing the entire terminal process group.",
  safetyLevel: "ddl",
  runIn: "shell",
  sessions: 1,
  estimatedMinutes: 30,
  code: RETRY_SCRIPT,
};
